### PR TITLE
Feat: Sanic Version Update

### PR DESCRIPTION
**Pull request by Safi-Ullah**

### CODE REVIEW

**Review by fenske — CHANGES_REQUESTED** [review]
@Safi-Ullah Could you double-check why the build is failing?

**Comment by Safi-Ullah** [comment]
> @Safi-Ullah Could you double-check why the build is failing?

I'll take a look at it.

**Comment by Safi-Ullah** [comment]
`Sanic`, no longer supports spaces in app name hence updated the app name.

**Comment by fenske** [comment]
Great find! LGTM.

**Pull request merged**
